-- CustomerPulse AI multi-tenant schema. Run with Supabase CLI.
create extension if not exists pgcrypto;
create extension if not exists vector;
create type public.app_role as enum ('administrator','sales_manager','marketing_manager','account_executive','auditor');
create type public.approval_status as enum ('draft','pending_approval','approved','rejected','changes_requested','cancelled','executed');

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, synthetic_demo boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users on delete cascade, organization_id uuid not null references public.organizations, display_name text not null, email text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,email));
create table public.user_roles (profile_id uuid not null references public.profiles on delete cascade, organization_id uuid not null references public.organizations, role app_role not null, created_at timestamptz not null default now(), primary key(profile_id,role));

create or replace function public.current_org_id() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from profiles where id=auth.uid() $$;
create or replace function public.has_role(wanted app_role[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from user_roles where profile_id=auth.uid() and role=any(wanted)) $$;

create table public.customers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, external_id text not null, customer_name text not null, company_name text, industry text, region text, assigned_profile_id uuid references profiles, email text, phone text, preferred_channel text, customer_since date, status text default 'active', deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.customer_consents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid not null references customers, purpose text not null, status text not null check(status in('granted','withdrawn','not_granted')), source text, captured_at timestamptz, withdrawn_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(customer_id,purpose));
create table public.products (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, sku text not null, name text not null, category text, description text, standard_price numeric(14,2), promotion_price numeric(14,2), promotion_start date, promotion_end date, inventory_status text, product_url text, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,sku));
create table public.transactions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, external_id text not null, customer_id uuid not null references customers, product_id uuid references products, transaction_date date not null, quantity numeric(12,2) not null, unit_price numeric(14,2) not null, total_amount numeric(14,2) not null, source_import_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.customer_products (organization_id uuid not null references organizations, customer_id uuid not null references customers, product_id uuid not null references products, first_purchase_at date, last_purchase_at date, total_value numeric(14,2) default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(customer_id,product_id));
create table public.conversations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, external_id text not null, customer_id uuid not null references customers, channel text not null, source text not null default 'import', deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, conversation_id uuid not null references conversations, external_id text not null, sender_type text not null check(sender_type in('customer','staff','system')), sender_name text, message_text text not null, sent_at timestamptz not null, attachment_path text, created_at timestamptz not null default now(), unique(organization_id,external_id));

create table public.import_jobs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, import_type text not null, filename text not null, storage_path text, status text not null, mapping jsonb default '{}', row_count int default 0, valid_count int default 0, invalid_count int default 0, duplicate_count int default 0, uploaded_by uuid references profiles, confirmed_by uuid references profiles, confirmed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.transactions add constraint transactions_import_fk foreign key(source_import_id) references import_jobs;
create table public.import_errors (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, import_job_id uuid not null references import_jobs on delete cascade, row_number int not null, field text, code text, message text not null, raw_row jsonb, created_at timestamptz not null default now());
create table public.uploaded_documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, import_job_id uuid references import_jobs, filename text not null, document_type text not null, storage_path text not null, owner_id uuid references profiles, classification text not null check(classification in('public','internal','confidential','restricted')), retention_category text not null, expires_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.document_chunks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, document_id uuid not null references uploaded_documents, page_number int, chunk_index int not null, chunk_location text, content text not null, embedding vector(1536), created_at timestamptz not null default now(), unique(document_id,chunk_index));

create table public.conversation_analyses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, conversation_id uuid not null references conversations, provider text not null, model text, is_demo boolean not null default false, output jsonb not null, confidence numeric(4,3), uncertainty_reason text, calculation_version text, created_by uuid references profiles, created_at timestamptz not null default now());
create table public.customer_tiers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid not null references customers, tier text not null, score numeric(5,2) not null, calculation_version text not null, manual_override boolean not null default false, override_reason text, override_user_id uuid references profiles, calculated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.tier_components (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_tier_id uuid not null references customer_tiers, component text not null, raw_value numeric, weighted_value numeric, source_ref jsonb, created_at timestamptz not null default now());
create table public.churn_scores (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid not null references customers, score int not null check(score between 0 and 100), risk_level text not null, confidence numeric(5,2), revenue_at_risk numeric(14,2), response_deadline timestamptz, top_factors jsonb not null default '[]', evidence jsonb not null default '[]', calculation_version text not null, manual_override boolean not null default false, override_reason text, override_user_id uuid references profiles, calculated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.churn_score_components (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, churn_score_id uuid not null references churn_scores, component text not null, raw_value numeric, weighted_value numeric, evidence jsonb, created_at timestamptz not null default now());
create table public.alerts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid references customers, alert_type text not null, title text not null, severity text not null, status text not null default 'New', evidence jsonb not null default '[]', assigned_profile_id uuid references profiles, deadline timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recommendations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid references customers, alert_id uuid references alerts, provider text not null, original_output jsonb not null, human_edited_output jsonb, action text, priority text, channel text, confidence text, uncertainty text, required_approver_role app_role, status approval_status not null default 'draft', owner_id uuid references profiles, deadline timestamptz, deleted_at timestamptz, created_by uuid references profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recommendation_feedback (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, recommendation_id uuid not null references recommendations, rating text not null check(rating in('useful','partially_useful','not_useful','incorrect')), correction_note text, created_by uuid not null references profiles, created_at timestamptz not null default now(), check(rating<>'incorrect' or correction_note is not null));

create table public.approval_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, entity_type text not null, entity_id uuid not null, requester_id uuid not null references profiles, required_role app_role not null, approver_id uuid references profiles, status approval_status not null default 'pending_approval', original_avo_output jsonb, human_edited_version jsonb, reviewer_comment text, rejection_reason text, before_state jsonb, after_state jsonb, submitted_at timestamptz not null default now(), approved_at timestamptz, execution_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(approver_id is null or approver_id<>requester_id));
create table public.approval_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, approval_request_id uuid not null references approval_requests, actor_id uuid not null references profiles, from_status approval_status, to_status approval_status not null, comment text, reason text, created_at timestamptz not null default now());
create table public.outreach_messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid not null references customers, recommendation_id uuid references recommendations, approval_request_id uuid references approval_requests, channel text not null, original_draft text, final_message text, trackable_url text, status approval_status not null default 'draft', creator_id uuid references profiles, approver_id uuid references profiles, executor_id uuid references profiles, executed_at timestamptz, customer_response text, final_outcome text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, customer_id uuid references customers, title text not null, owner_id uuid references profiles, status text not null default 'open', due_at timestamptz, completed_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.marketing_triggers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, segment_definition jsonb not null, affected_count int not null, affected_percentage numeric(5,2), revenue_decline numeric(6,2), frequency_decline numeric(6,2), engagement_decline numeric(6,2), common_factors jsonb, evidence jsonb, status text not null default 'new', deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, trigger_id uuid references marketing_triggers, name text not null, objective text, provider text, status approval_status not null default 'draft', current_version int not null default 1, created_by uuid references profiles, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.campaign_audiences (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, customer_id uuid not null references customers, consent_verified boolean not null, included boolean not null, exclusion_reason text, created_at timestamptz not null default now(), unique(campaign_id,customer_id));
create table public.campaign_sources (organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, document_id uuid not null references uploaded_documents, selected_by uuid references profiles, created_at timestamptz not null default now(), primary key(campaign_id,document_id));
create table public.campaign_assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, document_id uuid references uploaded_documents, storage_path text not null, mime_type text not null, alt_text text, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.campaign_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, version int not null, original_avo_output jsonb, content jsonb not null, factual_check jsonb, edited_by uuid references profiles, created_at timestamptz not null default now(), unique(campaign_id,version));
create table public.scheduled_posts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, approval_request_id uuid not null references approval_requests, publisher text not null, external_id text, channel_id text not null, content text not null, due_at timestamptz not null, status text not null, idempotency_key text not null, error text, retry_count int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,idempotency_key));
create table public.campaign_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid not null references campaigns, event_type text not null, channel text, count int default 1, value numeric(14,2), occurred_at timestamptz not null, created_at timestamptz not null default now());
create table public.link_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, campaign_id uuid references campaigns, outreach_message_id uuid references outreach_messages, token text not null unique, event_type text not null, occurred_at timestamptz not null default now(), metadata jsonb, created_at timestamptz not null default now());

create table public.governance_policies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, policy_type text not null, name text not null, configuration jsonb not null, enabled boolean not null default true, updated_by uuid references profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,policy_type,name));
create table public.data_retention_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, category text not null, retention_days int not null, enabled boolean not null default true, updated_by uuid references profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,category));
create table public.integration_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, integration text not null, configuration jsonb not null default '{}', secret_reference text, enabled boolean not null default false, updated_by uuid references profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,integration));
create table public.system_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, key text not null, value jsonb not null, updated_by uuid references profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,key));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations, actor_id uuid references profiles, actor_label text, actor_role text, action text not null, entity_type text not null, entity_id text, before_state jsonb, after_state jsonb, reason text, reviewer_comment text, correlation_id uuid not null default gen_random_uuid(), result text not null, created_at timestamptz not null default now());

create index customers_org_risk on customers(organization_id,external_id); create index transactions_customer_date on transactions(customer_id,transaction_date desc); create index messages_conversation_date on messages(conversation_id,sent_at); create index churn_customer_date on churn_scores(customer_id,calculated_at desc); create index alerts_org_status on alerts(organization_id,status,severity); create index audit_org_date on audit_logs(organization_id,created_at desc); create index approvals_org_status on approval_requests(organization_id,status); create index campaigns_org_status on campaigns(organization_id,status);

-- RLS: all tenant tables are isolated by current profile organisation. Mutations are further role-gated.
do $$ declare t text; begin foreach t in array array['profiles','user_roles','customers','customer_consents','products','transactions','customer_products','conversations','messages','import_jobs','import_errors','uploaded_documents','document_chunks','conversation_analyses','customer_tiers','tier_components','churn_scores','churn_score_components','alerts','recommendations','recommendation_feedback','approval_requests','approval_events','outreach_messages','tasks','marketing_triggers','campaigns','campaign_audiences','campaign_sources','campaign_assets','campaign_versions','scheduled_posts','campaign_events','link_events','governance_policies','data_retention_rules','integration_settings','system_settings','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select using (organization_id=public.current_org_id())',t||'_tenant_read',t); end loop; end $$;
create policy customer_ops on customers for all using (organization_id=current_org_id() and has_role(array['administrator','sales_manager','account_executive']::app_role[])) with check (organization_id=current_org_id() and has_role(array['administrator','sales_manager','account_executive']::app_role[]));
create policy import_admin on import_jobs for all using (organization_id=current_org_id() and has_role(array['administrator']::app_role[])) with check (organization_id=current_org_id() and has_role(array['administrator']::app_role[]));
create policy recommendations_ops on recommendations for all using (organization_id=current_org_id() and has_role(array['administrator','sales_manager','account_executive']::app_role[])) with check (organization_id=current_org_id() and has_role(array['administrator','sales_manager','account_executive']::app_role[]));
create policy approvals_manager on approval_requests for update using (organization_id=current_org_id() and has_role(array['administrator','sales_manager','marketing_manager']::app_role[])) with check (organization_id=current_org_id());
create policy campaigns_marketing on campaigns for all using (organization_id=current_org_id() and has_role(array['administrator','marketing_manager']::app_role[])) with check (organization_id=current_org_id() and has_role(array['administrator','marketing_manager']::app_role[]));
create policy governance_admin on governance_policies for all using (organization_id=current_org_id() and has_role(array['administrator']::app_role[])) with check (organization_id=current_org_id() and has_role(array['administrator']::app_role[]));
-- Intentionally no UPDATE or DELETE policy on audit_logs.
